services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tcit-sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Tcit_Challenge_Password!26"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - tcit-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tcit-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=sqlserver://db:1433;database=TcitChallengeDB;user=sa;password=Tcit_Challenge_Password!26;encrypt=false;trustServerCertificate=true;
    depends_on:
      - db
    networks:
      - tcit-network

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tcit-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - tcit-network

networks:
  tcit-network:
    driver: bridge